---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-audiobookshelf
  namespace: media
spec:
  stripPrefix:
    prefixes:
      - /audiobookshelf
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-audiobookshelf-prefix
  namespace: media
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Prefix: /audiobookshelf
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobookshelf
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: media-strip-audiobookshelf@kubernetescrd,media-add-audiobookshelf-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /audiobookshelf
            pathType: Prefix
            backend:
              service:
                name: audiobookshelf
                port:
                  number: 80
