apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: smb-csi-driver
  namespace: flux-system
spec:
  interval: 24h
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/release-1.20/charts
