apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: media-smb
provisioner: smb.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0775
  - file_mode=0664
  - uid=1000
  - gid=1000
  - vers=3.0
