apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      tag: v3.7.6
    ports:
      web:
        forwardedHeaders:
          trustedIPs:
            - 10.1.10.0/24
            - 10.1.40.0/24
      websecure:
        forwardedHeaders:
          trustedIPs:
            - 10.1.10.0/24
            - 10.1.40.0/24
      lms-web:
        port: 9000
        expose:
          default: true
        exposedPort: 9000
        protocol: TCP
        forwardedHeaders:
          trustedIPs:
            - 10.1.10.0/24
            - 10.1.40.0/24
