- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
