apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lyrion-config
spec:
  sourcePVC: lyrion-config
  trigger:
    schedule: "0 3 * * *"
  restic:
    pruneIntervalDays: 7
    repository: lyrion-config-volsync
    retain:
      daily: 7
      weekly: 4
    copyMethod: Direct
