apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /audiobookshelf(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: audiobookshelf
                port:
                  number: 80
          - path: /lms(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: lyrion
                port:
                  number: 9000
