apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audiobooks-pv.yaml
  - audiobooks-pvc.yaml
  - music-pv.yaml
  - music-pvc.yaml
  - music-flac-pv.yaml
  - music-flac-pvc.yaml
  - audiobookshelf-config-pvc.yaml
  - lyrion-config-pvc.yaml
