apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-flac
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: media-smb
  volumeName: music-flac
